### ISSUE TITLE
popup is partially shown when login button on top right corner

### ISSUE THREAD

**Issue by kfirufk** [Urigo/angular2-meteor-accounts-ui#10]
Hello.

I have an angular2-material toolbar that contains the loginButtons on the top right corner. when i click on it, the popup opens up and i can only see a small part of it. it adds a scroller to my page and i need to scroll right to see the rest of the popup. is there a way to tell it to open to the left instead of to the right of the login button ?

**Comment by Rahman-S-M** [comment]
I'm seeing the same issue. any way to open the popup on left ?

**Comment by dotansimha** [comment]
@kfirufk 
The login buttons are intended for scaffolding and provided as a quick solution for new applications, and I recommend to replace it in a growing project.
I still encourage you to fix it and PR us with a solution!
