### ISSUE TITLE
Unable to resolve some modules (css related?)

### ISSUE THREAD

**Issue by Ryuzavi** [Urigo/angular2-meteor-accounts-ui#11]
Hey

This was raised by someone else against the [angular2-meteor repository](https://github.com/Urigo/angular2-meteor/issues/256)  but it was closed and directed to be raised here.  It doesn't seem to have been raised so doing it now.

Getting a non blocking error regarding a missing module:

```
Unable to resolve some modules:

"!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in /E/meteor-projects/socially/node_modules/angular2-meteor-accounts-ui/login-buttons.js (web.browser)
```

It doesn't prevent running however, just a warning.

**Comment by twastvedt** [comment]
Hi @Ryuzavi. This is already being discussed and reported on here: #2. Come join us!

**Comment by Ryuzavi** [comment]
Ahh apologies.  Will close this one then
