### ISSUE TITLE
Please support Angular 2 rc1

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular2-meteor-accounts-ui#13]
Right now, if use this package, the console shows:

> Uncaught Error: Cannot find module 'angular2/core'

**Comment by ghost** [comment]
I second this. Need RC1 support asap or an update on whats happening?

**Comment by Tidio** [comment]
Hi, I encountered the same problem, it would be great to support Angular 2 rc1 since it have significant changes.
(Sorry for my english in advance).

**Comment by somombo** [comment]
I second this, kindly update.. Thank You!

**Comment by Urigo** [comment]
fixed and released a new version, please let me know if it's working for you now

**Comment by somombo** [comment]
Still getting the following error.. Please advise:

> "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./login-buttons.less" in
> /C/Users/chiso/Desktop/Development/angular/meteor/myappname/src/node_modules/angular2-meteor-accounts-ui/login-buttons.js
> (web.browser)
> 
> If you notice problems related to these missing modules, consider running:
> 
>   meteor npm install --save !!.

**Comment by Urigo** [comment]
@Makombo those warnings are tracked in [this issue](https://github.com/Urigo/angular2-meteor-accounts-ui/issues/12).
They won't interrupt your app and your app should work fine with them, it's just annoying and hopefully will be solved soon

**Comment by somombo** [comment]
Great Thank you!
