### ISSUE TITLE
Missing css in new version?

### ISSUE THREAD

**Issue by twastvedt** [Urigo/angular2-meteor-accounts-ui#14]
I just updated from 0.3.5 and am now (I think) not getting the css for the login menu. Before, I ended up with a `<style>` tag in the `<head>` with all of the styles for `.login-buttons`. Now there isn't one, which I'm assuming is why it's not working. Did I miss something?

**Comment by dotansimha** [comment]
That's correct.
With the latest version of Meteor you need to import the package CSS in your main JavaScript file. 

Please refer to [step 8 of the Angular2-Meteor tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions).
