### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on LoginButtons

### ISSUE THREAD

**Issue by gdomino** [Urigo/angular2-meteor-accounts-ui#19]
HI, I just cloned the code and am following the instructions in the Angular2 Meteor tutorial but keep receiving this error message EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on LoginButtons. As directed I added the following to my component where I want the module:

import {LoginButtons} from 'angular2-meteor-accounts-ui';

directives: [LoginButtons],

Any help would be appreciated.

**Comment by dotansimha** [comment]
I encounter this error in another case.
In some cases, when using Angular 2 and loading an external package that depends on Angular 2, a duplication of Angular 2 is created. you can identify this issue when you have the following files, for example:

```
- node_modules
   - @angular
   - angular2-meteor-accounts-ui
       - node_modules
            @angular
```

And when you have multiple Angular2 instances, it might use the inner Angular 2 to register the Component, and then it's not recognized in the project's files.

Please try to validate that you have only once existing package of Angular 2 (`@angular`) in your `node_modules`, you can also do it by running: `meteor npm dedupe`.

Please re-open if this solution does not solves your issue.
