### ISSUE TITLE
angular2-meteor-accounts-ui New router

### ISSUE THREAD

**Issue by puedesleerlo** [Urigo/angular2-meteor-accounts-ui#20]
Hello everyone, angular2-meteor-accounts-ui doesn't work with the new router, it ask by @angular/router-deprecated

**Comment by mariohmol** [comment]
I'm getting this , is the same error, right?

Any workaround?

```
Unable to resolve some modules:

  "@angular/router-deprecated/src/lifecycle/lifecycle_annotations_impl" in
/Users/mariohmol/projetos/brigadistacivilmobile/brigadistacivil/node_modules/angular2-meteor-accounts-ui/build/annotations.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @angular
```

**Comment by Rodix** [comment]
I'm get the same error

**Comment by mariohmol** [comment]
check this out.. angular2 changed a lot of things and broken meteor ang2 https://github.com/Urigo/angular2-meteor-accounts-ui/pull/22#issuecomment-232145684

**Comment by Rodix** [comment]
do you have some solution for this issue? at less a temperally solution?

**Comment by mariohmol** [comment]
do not use angular2-meteor modules to make auth.. i guess that meteor it self has everything to make it work.. but i dont know.. i stoped there and will not get back until have a final release..

**Comment by eric-burel** [comment]
A simple `meteor npm install --save @angular/router-deprecated` (then restart Meteor) solved this for me.

**Comment by mariohmol** [comment]
the thing is.. it will no longer exists or will not have support...so if you are planning to have a long term app.. its necessary other solution

**Comment by eric-burel** [comment]
Yes of course that's only a quickfix, I guess maintainers plan to change that when Angular API is stabilized

**Comment by mariohmol** [comment]
take a look https://github.com/Urigo/angular2-meteor-accounts-ui/pull/22#issuecomment-233221303

**Comment by Rodix** [comment]
@eric-burel   your solution works for me.

**Comment by dotansimha** [comment]
@eric-burel is right, adding the router-deprecated will solve this issue at the moment. 
In the future, we will try to implement a new solution for Angular 2 new router (which is still in development and it's API is not stabilized yet).
