### ISSUE TITLE
error with new form API of angular/forms 

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular2-meteor-accounts-ui#23]
Hi,
the use of this package throws error with the new form API:

```
 If ngModel is used within a form tag, either the name attribute must be set
```

If I'm not mistaken there is only the `name="x"` missing inside of the form input fields.

**Comment by eric-burel** [comment]
I just send a PR #24 to solve this, I simply added `name` attributes for email and password field as mentionned.
