### ISSUE TITLE
RequireUser not working

### ISSUE THREAD

**Issue by parwan-as** [Urigo/angular2-meteor-accounts-ui#26]
I'm following this [`tutorial`](https://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions) and my problem is that the annotation "@RequireUser" bugs everything, the only error that display at my chrome console is  :
`Uncaught ReferenceError: _super is not defined
RequireUserAnnotation @ annotations.js:46
DecoratorFactory @ decorators.js:179
(anonymous function) @ party-details.ts:14
meteorInstall.client.imports.party-details.party-details.ts @ party-details.ts:46
fileEvaluate @ install.js:153
require @ install.js:82
meteorInstall.client.app.ts @ app.ts:7
fileEvaluate @ install.js:153
require @ install.js:82
(anonymous function) @ parties.ts:22` 
and that error point out the @RequireUser annotation.

Does anyone know where the problem comes from ?
Here you can find the [`code sample`](https://gist.github.com/theasc/0b86634403c477463d4bedcb95c5ebfe)

**Comment by dotansimha** [comment]
Hi @theasc, can you provide your `package.json`? 
Are you using the latest version of `angular2-meteor` and `angular2-meteor-accounts-ui`?

Thanks.

**Comment by parwan-as** [comment]
Hi @dotansimha, I'm actually using the version  0.5.0 of angular2-meteor-accounts-ui 
and version 0.5.6 for angular2-meteor. 

Here is the [package.json](https://gist.github.com/theasc/ba741ca74d8da52adde70f1bcf72f408)

**Comment by dotansimha** [comment]
@theasc 
Please try to use the newer versions. 
`angular2-meteor` has 0.6.1 and `angular2-meteor-accounts-ui` has 0.6.1.

**Comment by parwan-as** [comment]
thanks @dotansimha  it worked.
