### ISSUE TITLE
RequireUser cannot resolve symbol

### ISSUE THREAD

**Issue by tna274** [Urigo/angular2-meteor-accounts-ui#27]
When I was imported 'RequireUser', have an error occurred: "Cannot resolve symbol 'RequireUser'"
I was try to found this export class/function RequireUser in node_module angular2-meteor-accounts-ui but there is not. I was found InjectUser only.
Someone can help?
I already use angular2-meteor v0.6.2 and angular2-meteor-accounts-ui v0.6.1.
Update: When I import RequireUser, my app run fine, but when I use function @RequireUser(), my app cant show anything, when I see console, It's show error message: 'TypeError: angular2_meteor_accounts_ui_1.RequireUser is not a function'

**Comment by deltaag** [comment]
https://github.com/Urigo/meteor-angular2.0-socially/issues/124#issue-166963967

**Comment by tna274** [comment]
thanks for answer, I will try!

**Comment by Urigo** [comment]
the tutorial was updated, please open a new issue if it's not working for you.
Thanks
