### ISSUE TITLE
Support creating username

### ISSUE THREAD

**Issue by twastvedt** [Urigo/angular2-meteor-accounts-ui#4]
`login-buttons.js` checks for `user.username` when getting `displayName`. However, I don't see any way to allow new users to set that field. Am I missing something?

**Comment by piavgh** [comment]
Hi @twastvedt 

Did you find the solution yet?

**Comment by twastvedt** [comment]
No, sorry, I haven't been looking into it.

**Comment by dotansimha** [comment]
You are right, at the moment it does not support it. (I encourage you to add this and PR !)
This login buttons should be used for scaffolding and I recommend to replace it with custom authorization component.
