### ISSUE TITLE
is there a support for accounts-facebook,twitter,google ?

### ISSUE THREAD

**Issue by kfirufk** [Urigo/angular2-meteor-accounts-ui#8]
Hello.

I'm new to using angular2 with meteor. and i'm wondering if there is a support for the login modules called accounts-facebook,accounts-google,accounts-twitter ?

i just want to know that they're supported and i'm missing something or if they're not supported yet.

thanks!

**Comment by dotansimha** [comment]
Hi @kfirufk 
We want to add support, but unfortunately it requires a lot of time. 

I encourage you to add support for those services and PR us. 

The actual implementation should be similar to the Blaze package that provides similar functionality, you can find it here:
https://github.com/meteor/meteor/tree/devel/packages/accounts-ui-unstyled 
https://github.com/meteor/meteor/tree/devel/packages/accounts-ui
